fun render(args: Array<String>) =
        html {
            head {
                title { +"The Title" }
            }
            body {
                h1 { +"Some Header" }
                p { +"Paragraph" }

                // an element with attributes and text content
                a(href = "http://kotlinlang.org") { +"Kotlin" }

                // mixed content
                p {
                    +"This is some"
                    b { +"mixed" }
                    +"text. For more see the"
                    a(href = "http://kotlinlang.org") { +"Kotlin" }
                    +"project"
                }
                p { +"some text" }

                // content generated by args
                p {
                    for (arg in args)
                        +arg
                }
            }
        }

fun main(args: Array<String>) {
    println(render(arrayOf("test")))
}